### ISSUE TITLE
Question: How to add custom header or API Key?

### ISSUE THREAD

**Issue by o-data** [taniarascia/sandbox#6]
Hi Tania,

Thank you for this guide: https://www.taniarascia.com/how-to-connect-to-an-api-with-javascript/

Manage to learn a lots from it.

What I wanted to ask is, with your API it is open and doesn't require any type of authentication, but most API require one. I been trying to adapt with your by adding these API authorization but having great difficulty doing it.

How do I add in a Custom Headers or API authentication with the Javascript code?

Thank you.

**Comment by taniarascia** [comment]
Hello,

Every API will have different headers and authentication that it requires. You can view [the Fetch API guide](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) to see how to add headers with fetch.
